name: Generate and publish Kaggle Dataset

permissions:
   contents: read

on:
  # TODO: add on-release
  workflow_dispatch:
  pull_request:

jobs:
  gen_op_exp_dataset:
    # TODO: activate in the production pipeline
    # if: github.repository == 'NMRLipids/BilayerData'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout BilayerData
        uses: actions/checkout@v6
        with:
          path: BilayerData

      - name: Checkout Databank API
        uses: actions/checkout@v6
        with:
          repository: NMRLipids/FAIRMD_lipids
          ref: datasets-generator
          path: Databank

      - name: Pin python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Databank API, Kaggle API
        working-directory: "Databank"
        run: |
          set -e
          pip install .
          pip install kaggle unidecode tables

      - name: Prepare dataset metadata
        env:
          TQDM_DISABLE: "True"
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
        working-directory: "BilayerData"
        run: |
          set -e
          mkdir dataset
          cd dataset
          kaggle datasets metadata fairmd/lipid-ch-order-parameters-from-md-simulations
          jq '{
            id: .info.datasetSlug,
            id_no: .info.datasetId,
            title: .info.datasetSlug,
            subtitle: (.info.subtitle // ""),
            description: (.info.description // "")
          }' dataset-metadata.json > tmp.json
          mv tmp.json dataset-metadata.json

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Prepare new data
        env:
          TQDM_DISABLE: "True"
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
          FMDL_DATA_PATH: ${{ github.workspace }}/BilayerData
        working-directory: "BilayerData"
        run: |
          set -e
          cd dataset
          python developer/gen-op-dataset.py --sims
          cd ..
          kaggle datasets version -p ./dataset -m "Dataset auto-release from ${SHORT_SHA}"

